language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
install:
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt
  - pip install .
before_script:
  - sleep 1
script:
  - pytest tests
after_success:
  - sleep 1